"""Hub — composable spokes, append-only run records, replayable proof.

Deterministic, offline, AI-free. See ``docs/contracts/hub-v1.md``.
"""

from godotforge_core.hub.definitions import (
    SPOKE_DEFINITION_SCHEMA_VERSION,
    Capability,
    Permission,
    ProviderDescriptor,
    SpokeDefinition,
)
from godotforge_core.hub.goal import (
    GOAL_SCHEMA_VERSION,
    ClarificationIssue,
    GoalCompilation,
    GoalSpec,
    compile_goal,
    compute_goal_hash,
    load_goal_text,
    registered_templates,
)
from godotforge_core.hub.registry import (
    SPOKE_LEDGER_SCHEMA_VERSION,
    ActiveRegistration,
    LedgerAction,
    RegistryState,
    SpokeEvent,
    compute_spoke_event_hash,
    deregister_spoke,
    fold_registry,
    invoke,
    ledger_path,
    read_ledger,
    register_spoke,
    resolve_capability,
    verify_ledger,
)
from godotforge_core.hub.run_record import (
    RUN_RECORD_SCHEMA_VERSION,
    Authorization,
    RunEvent,
    RunEventKind,
    RunRecord,
    RunState,
    append_event,
    compute_event_hash,
    compute_proof_hash,
    fold_run,
    read_events,
    run_store_path,
    verify_chain,
)

__all__ = [
    "GOAL_SCHEMA_VERSION",
    "RUN_RECORD_SCHEMA_VERSION",
    "SPOKE_DEFINITION_SCHEMA_VERSION",
    "SPOKE_LEDGER_SCHEMA_VERSION",
    "ActiveRegistration",
    "Authorization",
    "Capability",
    "ClarificationIssue",
    "GoalCompilation",
    "GoalSpec",
    "LedgerAction",
    "Permission",
    "ProviderDescriptor",
    "RegistryState",
    "RunEvent",
    "RunEventKind",
    "RunRecord",
    "RunState",
    "SpokeDefinition",
    "SpokeEvent",
    "append_event",
    "compile_goal",
    "compute_event_hash",
    "compute_goal_hash",
    "compute_proof_hash",
    "compute_spoke_event_hash",
    "deregister_spoke",
    "fold_registry",
    "fold_run",
    "invoke",
    "ledger_path",
    "load_goal_text",
    "read_events",
    "read_ledger",
    "register_spoke",
    "registered_templates",
    "resolve_capability",
    "run_store_path",
    "verify_chain",
    "verify_ledger",
]
