"""Goal compilation — structured GoalSpec → CreatorManifest (schema v2).

The goal is the user-facing input to the Hub. v1 accepts **structured
YAML/JSON only** — no natural-language interpretation anywhere in this
module. Compilation is pure: no filesystem mutation, no subprocess, no
network, no AI/model calls, no asset downloads.

Authority boundaries (locked):

- The goal is never a second authority for behavior versions, resource pins,
  numeric formatting, or generated bytes. It carries a template id and
  optional typed parameters only; behavior selection, ranges, canonical
  numerics, and byte emission stay with ``creator/manifest.py``,
  ``creator/numfmt.py``, and the behavior registry.
- Compilation reuses the existing Decimal-preserving ingestion boundary
  (``creator/loading.py``), the v2 manifest validator, and the template
  allowlist below. A compiled goal's manifest is byte-identical to the
  equivalent hand-written v2 manifest.
- Defaults are resolved **explicitly** and recorded in
  ``GoalSpec.resolved_defaults``; nothing is hidden inside execution.
- Missing high-impact information (game name, template) returns a
  structured clarification result — never an invented assumption.
- Unknown templates, keys, parameters, malformed values, invalid ranges,
  unsupported behavior requests, and path-shaped strings are rejected with
  ``ValueError``.

Offline/single-user mode: no access control or rate limiting. Network exposure
requires separate hardening.

See ``docs/contracts/hub-v1.md`` §8 and ``schemas/goal.schema.json``.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import jsonschema

from godotforge_core.creator.loading import load_json_manifest, load_yaml_manifest
from godotforge_core.creator.manifest import (
    BehaviorParameters,
    CreatorManifest,
    validate_manifest_dict,
)

GOAL_SCHEMA_VERSION = 1

# Fixed inputs for the only v1 template — identical to the manifest contract
# (creator/manifest.py _FIXED_BINDINGS). The goal carries no input section;
# these are compiled in, and the manifest validator remains the authority.
_FIXED_INPUTS: tuple[dict[str, str], ...] = (
    {"name": "move_left", "binding": "ui_left"},
    {"name": "move_right", "binding": "ui_right"},
    {"name": "jump", "binding": "ui_accept"},
)

_ALLOWED_TOP_LEVEL_KEYS = frozenset({"schema_version", "game", "parameters"})
_ALLOWED_GAME_KEYS = frozenset({"name", "template"})
_ALLOWED_BEHAVIOR_KEYS = frozenset({"platformer_controller"})
_ALLOWED_PARAMETER_KEYS = frozenset({"speed", "jump_velocity"})

# Path-shaped strings can never be valid here: game.name is restricted to
# ^[A-Za-z0-9 _-]+$ by the manifest validator, and these guards make the
# rejection explicit for absolute paths and traversal attempts.
_PATH_LIKE_PATTERN = re.compile(r"(^/|^[A-Za-z]:[\\/]|\\\\|\.\.|//|res://|uid://)")

# Explicit template registry — the only templates a goal may name. Maps
# template id → the CreatorManifest schema version it compiles to. Behavior
# identity/version are *not* restated here; the manifest validator and the
# behavior registry own those.
_TEMPLATES: dict[str, int] = {
    "2d-platformer-minimal": 2,
}


def registered_templates() -> tuple[str, ...]:
    """registered_templates — sorted tuple of goal-compilable template ids."""
    return tuple(sorted(_TEMPLATES))


@dataclass(frozen=True)
class ClarificationIssue:
    """ClarificationIssue — structured request for missing information."""

    field: str
    kind: str
    message: str

    def as_dict(self) -> dict[str, str]:
        """as_dict — canonical serialization."""
        return {"field": self.field, "kind": self.kind, "message": self.message}


@dataclass(frozen=True)
class GoalSpec:
    """GoalSpec — canonical resolved goal, defaults made explicit.

    ``parameters`` always holds fully resolved values (Decimal, canonical);
    ``resolved_defaults`` records every parameter that took its contract
    default so resolution is auditable. The original user input is kept
    separately in :class:`GoalCompilation` — never merged into the spec.
    """

    game_name: str
    template: str
    parameters: BehaviorParameters
    resolved_defaults: tuple[str, ...]
    schema_version: int = GOAL_SCHEMA_VERSION

    def as_dict(self) -> dict[str, Any]:
        """as_dict — canonical serialization matching goal.schema.json shape."""
        return {
            "schema_version": self.schema_version,
            "game": {"name": self.game_name, "template": self.template},
            "parameters": self.parameters.as_dict(),
        }


@dataclass(frozen=True)
class GoalCompilation:
    """GoalCompilation — outcome of compiling one structured goal document.

    ``status`` is ``"ok"`` with a fully resolved :class:`GoalSpec`, the
    equivalent v2 manifest dict, and the canonical ``goal_hash``; or
    ``"clarification"`` with structured issues and no goal. ``raw_input``
    always preserves the original parsed user document, untouched.
    """

    status: str
    raw_input: dict[str, Any]
    issues: tuple[ClarificationIssue, ...]
    goal: GoalSpec | None
    manifest_dict: dict[str, Any] | None
    goal_hash: str | None


# Load goal schema for validation
_GOAL_SCHEMA = None


def _load_goal_schema() -> dict[str, Any]:
    """_load_goal_schema — load and cache the goal JSON schema."""
    global _GOAL_SCHEMA
    if _GOAL_SCHEMA is None:
        schema_path = Path(__file__).parent.parent / "schemas" / "goal.schema.json"
        with schema_path.open("r", encoding="utf-8") as f:
            _GOAL_SCHEMA = json.load(f)
    return _GOAL_SCHEMA


MAX_GOAL_FILE_SIZE = 1024 * 1024  # 1MB


def _validate_goal_schema(data: dict[str, Any]) -> None:
    """_validate_goal_schema — validate parsed goal data against goal.schema.json."""
    schema = _load_goal_schema()
    jsonschema.validate(data, schema)


def _reject_path_like_in_mapping(data: dict[str, Any], *, prefix: str = "") -> None:
    """_reject_path_like_in_mapping — recursively reject path-like strings in any field."""
    for key, value in data.items():
        field = f"{prefix}.{key}" if prefix else key
        if isinstance(value, str):
            _reject_path_like(value, field=field)
        elif isinstance(value, dict):
            _reject_path_like_in_mapping(value, prefix=field)
        elif isinstance(value, list):
            for i, item in enumerate(value):
                if isinstance(item, str):
                    _reject_path_like(item, field=f"{field}[{i}]")
                elif isinstance(item, dict):
                    _reject_path_like_in_mapping(item, prefix=f"{field}[{i}]")


def _reject_path_like(value: str, *, field: str) -> None:
    """_reject_path_like — reject absolute paths, traversal, and URIs."""
    if _PATH_LIKE_PATTERN.search(value):
        raise ValueError(f"{field} must not contain paths or traversal: {value!r}")


def load_goal_text(text: str, *, format: str = "yaml") -> dict[str, Any]:
    """load_goal_text — parse structured YAML/JSON goal text via the shared
    Decimal-preserving, duplicate-rejecting ingestion boundary.

    ``format`` is ``"yaml"`` or ``"json"``. Raises ``ValueError`` for
    non-mapping documents, duplicates, or unknown formats. No file I/O.
    """
    if format == "yaml":
        return load_yaml_manifest(text)
    if format == "json":
        return load_json_manifest(text)
    raise ValueError(f"goal format must be 'yaml' or 'json', got {format!r}")


def load_goal_file(path: Path | str, *, format: str = "yaml") -> dict[str, Any]:
    """load_goal_file — load and validate a goal file from disk.

    Performs the following validations before parsing:
    - File size must not exceed 1MB.
    - File content must be valid YAML/JSON (via load_goal_text).
    - Parsed content must validate against goal.schema.json.
    - No string field may contain path-like patterns (absolute paths,
      traversal ``..``, ``//``, ``res://``, ``uid://``).

    Args:
        path: Path to the goal file.
        format: ``"yaml"`` or ``"json"``.

    Returns:
        Parsed and validated goal dict.

    Raises:
        ValueError: If file is too large, format is invalid, schema validation
            fails, or path-like strings are detected.
        FileNotFoundError: If the file does not exist.
    """
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"goal file not found: {path}")

    # Check file size
    file_size = path.stat().st_size
    if file_size > MAX_GOAL_FILE_SIZE:
        raise ValueError(f"goal file exceeds 1MB limit: {file_size} bytes")

    text = path.read_text(encoding="utf-8")
    data = load_goal_text(text, format=format)

    # Path traversal rejection on all string fields (before schema validation
    # so we catch traversal attempts with a clear error message)
    _reject_path_like_in_mapping(data)

    # Schema validation
    _validate_goal_schema(data)

    return data


def _resolve_parameters(raw: Any) -> tuple[dict[str, Any], tuple[str, ...]]:
    """_resolve_parameters — validate shape, record which values default.

    Returns the parameters sub-dict to embed in the manifest (only explicitly
    supplied keys; the manifest validator applies canonical defaults and
    ranges) plus the dotted paths that will take defaults. Range, precision,
    and canonical-format enforcement stay with ``validate_manifest_dict``.
    """
    prefix = "parameters.platformer_controller"
    if raw is None:
        return {}, (f"{prefix}.speed", f"{prefix}.jump_velocity")
    if not isinstance(raw, dict):
        raise ValueError(f"parameters must be a mapping, got {raw!r}")
    unknown_behaviors = set(raw) - _ALLOWED_BEHAVIOR_KEYS
    if unknown_behaviors:
        raise ValueError(
            f"unsupported behavior request(s): {sorted(unknown_behaviors)}; "
            f"supported: {sorted(_ALLOWED_BEHAVIOR_KEYS)}"
        )
    behavior = raw.get("platformer_controller")
    if behavior is None:
        return {}, (f"{prefix}.speed", f"{prefix}.jump_velocity")
    if not isinstance(behavior, dict):
        raise ValueError(f"parameters.platformer_controller must be a mapping, got {behavior!r}")
    unknown_params = set(behavior) - _ALLOWED_PARAMETER_KEYS
    if unknown_params:
        raise ValueError(
            f"unknown parameter(s): {sorted(unknown_params)}; "
            f"supported: {sorted(_ALLOWED_PARAMETER_KEYS)}"
        )
    defaults = tuple(
        f"{prefix}.{name}" for name in ("speed", "jump_velocity") if name not in behavior
    )
    return {"platformer_controller": dict(behavior)}, defaults


def compile_goal(data: dict[str, Any]) -> GoalCompilation:
    """compile_goal — compile a parsed goal document into a v2 CreatorManifest.

    Pure and deterministic. Raises ``ValueError`` for unknown keys/templates/
    parameters, malformed values, invalid ranges (via the manifest
    validator), and path-like strings. Returns ``status="clarification"``
    when high-impact information (game name, template) is missing.
    """
    if not isinstance(data, dict):
        raise ValueError("goal must be a mapping")

    # Path traversal rejection on all string fields (defense in depth for
    # callers that bypass load_goal_file)
    _reject_path_like_in_mapping(data)

    schema_version = data.get("schema_version")
    if isinstance(schema_version, bool) or not isinstance(schema_version, int):
        raise ValueError(
            f"schema_version must be int {GOAL_SCHEMA_VERSION}, got {schema_version!r}"
        )
    if schema_version != GOAL_SCHEMA_VERSION:
        raise ValueError(f"schema_version must be {GOAL_SCHEMA_VERSION}, got {schema_version!r}")
    unknown_top = set(data) - _ALLOWED_TOP_LEVEL_KEYS
    if unknown_top:
        raise ValueError(f"unknown top-level goal key(s): {sorted(unknown_top)}")

    game = data.get("game")
    issues: list[ClarificationIssue] = []
    if not isinstance(game, dict):
        issues.append(
            ClarificationIssue(
                field="game",
                kind="missing_required",
                message="game section is required: provide game.name and game.template",
            )
        )
        return GoalCompilation(
            status="clarification",
            raw_input=data,
            issues=tuple(issues),
            goal=None,
            manifest_dict=None,
            goal_hash=None,
        )
    unknown_game = set(game) - _ALLOWED_GAME_KEYS
    if unknown_game:
        raise ValueError(f"unknown game key(s): {sorted(unknown_game)}")

    name = game.get("name")
    template = game.get("template")
    if not isinstance(name, str) or not name:
        issues.append(
            ClarificationIssue(
                field="game.name",
                kind="missing_required",
                message=(
                    "game.name is required: a short title (1-64 chars, letters/digits/space/_/-)"
                ),
            )
        )
    else:
        _reject_path_like(name, field="game.name")
    if not isinstance(template, str) or not template:
        issues.append(
            ClarificationIssue(
                field="game.template",
                kind="missing_required",
                message=(f"game.template is required: one of {list(registered_templates())}"),
            )
        )
    if issues:
        return GoalCompilation(
            status="clarification",
            raw_input=data,
            issues=tuple(issues),
            goal=None,
            manifest_dict=None,
            goal_hash=None,
        )

    assert isinstance(name, str) and isinstance(template, str)
    if template not in _TEMPLATES:
        raise ValueError(
            f"unknown template {template!r}; supported: {list(registered_templates())}"
        )

    parameters_dict, resolved_defaults = _resolve_parameters(data.get("parameters"))

    manifest_dict: dict[str, Any] = {
        "schema_version": _TEMPLATES[template],
        "game": {"name": name, "template": template},
        "input": [dict(entry) for entry in _FIXED_INPUTS],
        "parameters": parameters_dict,
    }
    # The manifest validator is the single authority for name pattern,
    # ranges, canonical numerics, and unknown keys; failures propagate as
    # ValueError (validation failure), never clarification guesses.
    manifest: CreatorManifest = validate_manifest_dict(manifest_dict)
    assert manifest.parameters is not None

    goal = GoalSpec(
        game_name=name,
        template=template,
        parameters=manifest.parameters,
        resolved_defaults=resolved_defaults,
    )
    return GoalCompilation(
        status="ok",
        raw_input=data,
        issues=(),
        goal=goal,
        manifest_dict=manifest.as_dict(),
        goal_hash=compute_goal_hash(goal),
    )


def compute_goal_hash(goal: GoalSpec) -> str:
    """compute_goal_hash — canonical SHA-256 of the fully resolved goal.

    Deterministic across runs/platforms; identical for explicitly supplied
    defaults and omitted defaults (canonical normalization happens first).
    """
    canonical = json.dumps(
        goal.as_dict(), sort_keys=True, separators=(",", ":"), ensure_ascii=False
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()
