import pytest
from godotforge_core.patch.models import (
    ALLOWED_TRANSITIONS,
    BackupRecord,
    Conflict,
    OperationKind,
    PatchOperation,
    PatchPlan,
    PatchResult,
    Transaction,
    TransactionStatus,
    can_transition,
)

HASH = "a" * 64
HASH2 = "b" * 64


def test_operation_create_update_delete_mkdir() -> None:
    for kind in (
        OperationKind.CREATE,
        OperationKind.UPDATE,
        OperationKind.DELETE,
        OperationKind.MKDIR,
    ):
        op = PatchOperation(
            kind=kind,
            path="scripts/foo.gd",
            owner="forge",
            reason="test",
        )
        assert op.path == "scripts/foo.gd"
        assert op.from_path is None
        assert op.to_path is None
        # round-trip via dict
        d = op.as_dict()
        assert d["path"] == "scripts/foo.gd"
        assert "from" not in d and "to" not in d
        assert PatchOperation.from_dict(d) == op


def test_operation_rename_explicit_fields() -> None:
    op = PatchOperation(
        kind=OperationKind.RENAME,
        from_path="scripts/old.gd",
        to_path="scripts/new.gd",
        owner="asset-studio",
        reason="Rename",
    )
    assert op.path is None
    d = op.as_dict()
    assert d["from"] == "scripts/old.gd"
    assert d["to"] == "scripts/new.gd"
    assert "path" not in d
    # from_dict supports external "from"/"to"
    assert PatchOperation.from_dict(d) == op
    # also supports internal names
    d2 = {
        "kind": "rename",
        "from_path": "scripts/old.gd",
        "to_path": "scripts/new.gd",
        "owner": "forge",
        "reason": "x",
    }
    assert PatchOperation.from_dict(d2).from_path == "scripts/old.gd"


def test_operation_rename_validation() -> None:
    with pytest.raises(ValueError, match="path=None"):
        PatchOperation(
            kind=OperationKind.RENAME,
            path="x",
            from_path="a",
            to_path="b",
            owner="forge",
            reason="x",
        )
    with pytest.raises(ValueError, match="from_path and to_path"):
        PatchOperation(  # type: ignore[arg-type]
            kind=OperationKind.RENAME, from_path="a", owner="forge", reason="x"
        )
    with pytest.raises(ValueError, match="must differ"):
        PatchOperation(
            kind=OperationKind.RENAME,
            from_path="same",
            to_path="same",
            owner="forge",
            reason="x",
        )
    with pytest.raises(ValueError, match="requires path"):
        PatchOperation(kind=OperationKind.CREATE, owner="forge", reason="x")


def test_owner_validation() -> None:
    valid = [
        "forge",
        "user",
        "asset-studio",
        "provider:godotsteam",
        "template:player-controller",
        "generator:scene",
        "a1",
        "my_owner-123",
        "a.b_c:d-e",
    ]
    for owner in valid:
        op = PatchOperation(kind=OperationKind.CREATE, path="a", owner=owner, reason="x")
        assert op.owner == owner

    invalid = [
        "",
        "Generated by Forge",
        "Asset Studio / Cover Low",
        "Forge Owner!",
        "UPPER",
        "123abc",
        "a..b",
        "a-",
    ]
    for owner in invalid:
        with pytest.raises(ValueError, match="invalid owner"):
            PatchOperation(kind=OperationKind.CREATE, path="a", owner=owner, reason="x")


def test_hash_validation() -> None:
    op = PatchOperation(
        kind=OperationKind.UPDATE,
        path="a",
        expected_hash=HASH,
        desired_hash=HASH2,
        owner="forge",
        reason="x",
    )
    assert op.expected_hash == HASH
    with pytest.raises(ValueError, match="invalid expected_hash"):
        PatchOperation(
            kind=OperationKind.UPDATE,
            path="a",
            expected_hash="abc",
            owner="forge",
            reason="x",
        )
    with pytest.raises(ValueError, match="invalid desired_hash"):
        PatchOperation(
            kind=OperationKind.UPDATE,
            path="a",
            desired_hash="ZZZ",
            owner="forge",
            reason="x",
        )


def test_path_validation() -> None:
    with pytest.raises(ValueError, match="relative"):
        PatchOperation(kind=OperationKind.CREATE, path="/abs", owner="forge", reason="x")
    with pytest.raises(ValueError, match="relative"):
        PatchOperation(kind=OperationKind.CREATE, path="C:/win", owner="forge", reason="x")
    with pytest.raises(ValueError, match="\\.\\."):
        PatchOperation(kind=OperationKind.CREATE, path="../escape", owner="forge", reason="x")
    with pytest.raises(ValueError, match="must not contain"):
        PatchOperation(kind=OperationKind.CREATE, path="a//b", owner="forge", reason="x")
    with pytest.raises(ValueError, match="must use '/'"):
        PatchOperation(kind=OperationKind.CREATE, path="a\\b", owner="forge", reason="x")


def test_plan_id_validation() -> None:
    valid = ["player-controller-v2", "a", "A1._:-b", "x" * 128]
    for pid in valid:
        plan = PatchPlan(id=pid, operations=())
        assert plan.id == pid
    invalid = ["", "-bad", ".bad", "a" * 129, "bad!", " bad"]
    for pid in invalid:
        with pytest.raises(ValueError, match="invalid plan id"):
            PatchPlan(id=pid, operations=())


def test_plan_serialization() -> None:
    op = PatchOperation(kind=OperationKind.CREATE, path="a/b", owner="forge", reason="r")
    plan = PatchPlan(id="my-plan_1", operations=(op,), created_at="2026-01-01T00:00:00Z")
    d = plan.as_dict()
    assert d["id"] == "my-plan_1"
    assert len(d["operations"]) == 1
    assert PatchPlan.from_dict(d) == plan


def test_transaction_and_transition_table() -> None:
    plan = PatchPlan(id="p1", operations=())
    tx = Transaction(id="t1", plan=plan, status=TransactionStatus.PLANNED)
    assert tx.status == TransactionStatus.PLANNED
    # valid transitions
    assert can_transition(TransactionStatus.PLANNED, TransactionStatus.PREVIEWED)
    assert can_transition(TransactionStatus.PREVIEWED, TransactionStatus.APPROVED)
    assert can_transition(TransactionStatus.APPROVED, TransactionStatus.APPLYING)
    assert can_transition(TransactionStatus.APPLYING, TransactionStatus.VALIDATED)
    assert can_transition(TransactionStatus.VALIDATED, TransactionStatus.COMMITTED)
    assert can_transition(TransactionStatus.APPLYING, TransactionStatus.FAILED)
    assert can_transition(TransactionStatus.FAILED, TransactionStatus.ROLLED_BACK)
    # invalid
    assert not can_transition(TransactionStatus.PLANNED, TransactionStatus.COMMITTED)
    assert not can_transition(TransactionStatus.COMMITTED, TransactionStatus.PLANNED)
    assert not can_transition(TransactionStatus.ROLLED_BACK, TransactionStatus.PLANNED)
    assert not can_transition(TransactionStatus.COMMITTED, TransactionStatus.FAILED)
    # also test via ALLOWED directly
    for src, targets in ALLOWED_TRANSITIONS.items():
        for tgt in targets:
            assert can_transition(src, tgt)
        # self not allowed unless explicitly
        if src not in targets:
            assert not can_transition(src, src)


def test_backup_record() -> None:
    br = BackupRecord(path="a/b", backup_path="/tmp/bak/a/b", hash=HASH, existed=True)
    d = br.as_dict()
    assert BackupRecord.from_dict(d) == br
    with pytest.raises(ValueError):
        BackupRecord(path="/abs", backup_path="x", hash=HASH, existed=True)


def test_conflict() -> None:
    op = PatchOperation(kind=OperationKind.UPDATE, path="a", owner="forge", reason="x")
    c = Conflict(
        path="a",
        expected_hash=HASH,
        actual_hash=HASH2,
        operation=op,
        reason="hash mismatch",
    )
    d = c.as_dict()
    assert Conflict.from_dict(d) == c
    with pytest.raises(ValueError):
        Conflict(path="a", expected_hash=HASH, actual_hash=HASH2, operation=op, reason="")


def test_patch_result() -> None:
    pr = PatchResult(transaction_id="tx1", status=TransactionStatus.COMMITTED, applied=2, skipped=0)
    d = pr.as_dict()
    assert PatchResult.from_dict(d) == pr
    with pytest.raises(ValueError):
        PatchResult(transaction_id="", status=TransactionStatus.FAILED)


def test_frozen() -> None:
    op = PatchOperation(kind=OperationKind.CREATE, path="a", owner="forge", reason="x")
    with pytest.raises(AttributeError):
        op.path = "b"  # type: ignore[misc]


def test_operation_as_dict_stable_enums() -> None:
    op = PatchOperation(kind=OperationKind.CREATE, path="a", owner="forge", reason="x")
    d = op.as_dict()
    assert d["kind"] == "create"  # not OperationKind enum
    assert isinstance(d["kind"], str)
